def form():
    print('1 - Encriptar Arquivos')
    print('2 - Decriptar Arquivos')
    print('3 - Encriptar Nomes')
    print('4 - Decriptar Nomes')
    print('5 - Gerar chave')
    print('6 - Encriptar chave')
    print('7 - Decriptar chave')
    print('0 - Sair')
    return input('-> ')